### ISSUE TITLE
Test Result Reporter

### ISSUE THREAD

**Issue by akhmadnurmuhammad** [jenkins-infra/repository-permissions-updater#2308]
### Repository URL

https://github.com/akhmadnurmuhammad/qa-matrix-jenkins-plugin

### New Repository Name

qa-matrix-plugin

### Description

this plugin allow to automated post test result to our service, this plugin help QA engineer job to make easier and more clean

### GitHub users to have commit permission

basil

### Jenkins project users to have release permission

basil

### Issue tracker

Github Tracker

**Comment by timja** [comment]
> /hosting host

Nice try, it needs one of the hosting team to do that 

---

Initial review without looking at the code much:

1. You're missing a .gitignore file, our template is at https://github.com/jenkinsci/archetypes/blob/master/common-files/gitignore
2. Delete the `target` and `work` directories, you probably want to remove your git history so the binaries are not stored in history
3. Use your artifact id for the package name: https://github.com/akhmadnurmuhammad/test-result-reporter-jenkins-plugin/tree/develop/src/main/java/io/jenkins/plugins/sample not sample
4. Name your class something meaningful not helloworld

What does this plugin actually do? the name is very generic?

**Comment by daniel-beck** [comment]
> not sample

There's also still https://github.com/akhmadnurmuhammad/test-result-reporter-jenkins-plugin/blob/a412ce1b124da64f0e746be1e9bdeec9cde5cd64/src/main/java/io/jenkins/plugins/sample/HelloWorldBuilder.java#L99-L117 from the sample plugin which will be reflected in serialized configuration and behavior, as well as https://github.com/akhmadnurmuhammad/test-result-reporter-jenkins-plugin/blob/a412ce1b124da64f0e746be1e9bdeec9cde5cd64/src/main/java/io/jenkins/plugins/sample/HelloWorldBuilder.java#L187-L197

> the name is very generic

I suggest the name be changed to include the name of the service it integrates with.

**Comment by daniel-beck** [comment]
The plugin requires Java 11 to build but still claims 8 at https://github.com/akhmadnurmuhammad/test-result-reporter-jenkins-plugin/blob/a412ce1b124da64f0e746be1e9bdeec9cde5cd64/pom.xml#L18

**Comment by akhmadnurmuhammad** [comment]
Hi all, thanks for correction but i cannot build at java, the build is successfully by my plugins missing in build step, after i saw the error message, the message return like this, can you help me? 

Caused by: java.lang.AssertionError: class io.jenkins.plugins.QaMatrixBuilder is missing its descriptor
        at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1599)
        at hudson.tasks.Builder.getDescriptor(Builder.java:67)

**Comment by timja** [comment]
The bot also runs on edits which is why it has been double running.

Maybe this needs bolding

> You can re-trigger a check by **editing your hosting request** or by commenting

**Comment by akhmadnurmuhammad** [comment]
sorry my bad

**Comment by daniel-beck** [comment]
Plugin still has an incorrect version requirement in the pom. Did you ever actually fully build this?

**Comment by timja** [comment]
Plugin pom should be the latest version, the minimum requirement of 4.0 just means it must be 4.x
Lots has changed since then.

Where did this come from?
https://github.com/akhmadnurmuhammad/qa-matrix-jenkins-plugin/blob/a284d2b3791283a3cccdd3a31badd4a5d08765e5/pom.xml#L35-L42

It seems like you've built it from an old version of the archetypes, you should have a URL set there and it should point to GitHub

Your code should be in a package named after your artifact id, i.e. not just in `io.jenkins.plugins`
https://github.com/akhmadnurmuhammad/qa-matrix-jenkins-plugin/tree/master/src/main/java/io/jenkins/plugins

Parameters and fields should follow Java naming, `reportName` rather than `ReportName`.

There should be a cleaner way of doing this than building it up yourself:
https://github.com/akhmadnurmuhammad/qa-matrix-jenkins-plugin/blob/master/src/main/java/io/jenkins/plugins/QaMatrixBuilder.java#L149-L161

There's no tests included, you might want to take a look at an example `Builder` test we provide:
https://github.com/jenkinsci/archetypes/blob/master/hello-world/src/main/resources/archetype-resources/src/test/java/HelloWorldBuilderTest.java

**Comment by timja** [comment]
@basil is this supposed to have you as the committer and release permissions?

**Comment by basil** [comment]
> @basil is this supposed to have you as the committer and release permissions?

No. Perhaps a copy-paste error?

**Comment by Wadeck** [comment]
@akhmadnurmuhammad Is there still an interest from you to host this plugin? Asking as it's since Jan we had not heard from you.

I did a superficial security audit, and my gut feeling is that the [QaMatrixBuilder.java#L42](https://github.com/akhmadnurmuhammad/qa-matrix-jenkins-plugin/blob/a284d2b3791283a3cccdd3a31badd4a5d08765e5/src/main/java/io/jenkins/plugins/QaMatrixBuilder.java#L42) should be a secret, but not sure as the code does not describe what that Token is supposed to be.

/audit-findings

If that token is not expected to related to any authentication mechanism, please tell us (and improve the comments/documentation around it to ease future audit)

**Comment by NotMyFault** [comment]
Hey @akhmadnurmuhammad,

are you still interested in this hosting request? If so, please address the open concerns. If not, I'll go ahead and close this request, given there's been no activity in over 9 months.

**Comment by NotMyFault** [comment]
I'll go ahead and close this request due to lack of response. If you are still interested in continuing with this request, please open a new issue.
